#!/bin/bash

if [ $# -eq 0 ]; then
    DATA_DIR="$HOME/.local/data/bagus"
    mkdir -p "$DATA_DIR"
    python3 /home/$USER/.local/bin/bagus/run.py "$DATA_DIR"
else
    python3 /home/$USER/.local/bin/bagus/run.py "$@"
fi
